# Generated by Django 5.0.6 on 2024-06-06 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todotask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 6, 17, 34, 54, 990559, tzinfo=datetime.timezone.utc)),
        ),
    ]
