# Generated by Django 5.0.6 on 2024-06-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todotask_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='date',
            field=models.DateField(auto_now=True, db_index=True),
        ),
    ]
